defaults:
  - datasets: datasets
  #- models: models
  - _self_

hydra:
  run:
    dir: ./logs/output/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ./logs/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
 